# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    env:
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/Bytom.sln

      - name: Build
        run: dotnet build --no-restore ./src/Bytom.sln

      - name: Test with coverage
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" ./src/Bytom.sln --results-directory=coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS
          directory: ./coverage/
          fail_ci_if_error: false
          flags: jest
          verbose: true
